ktor:
    application:
        modules:
            - jp.ac.it_college.std.s24009.kotlin.ktor.book.manager.ApplicationKt.module
    deployment:
        port: 8080
database:
  url: "jdbc:postgresql://localhost:5432/book_manager"
  driver: "org.postgresql.Driver"
  user: "book_manager"
  password: "ktor+exposed: password"